export {
  parseLearnerProfile,
  neutralLearnerProfile,
  resetLearnerProfile,
  profileForConstruction
} from './learnerProfile';
export type {
  LearnerConsent,
  LearnerProfileV1,
  PreferenceWeight
} from './learnerProfile';
export {
  assertValidPuzzle,
  createFixturePuzzle,
  createLargeFixturePuzzle,
  createRealPuzzle,
  deriveEntryNumbers,
  getCellPosition,
  getEntryForCell,
  indexPuzzle,
  isSupportedCrosswordAnswer,
  parsePuzzle,
  normalizeCrosswordAnswer,
  serializePuzzle,
  validatePuzzle
} from './puzzle';
export type {
  Cell,
  CellId,
  Direction,
  Entry,
  EntryId,
  PuzzleDocument,
  PuzzleId,
  PuzzleIndex,
  PuzzleManifest,
  PuzzleProvenance,
  PuzzleSource,
  PuzzleTopology,
  ClueMechanism,
  ClueSet,
  ClueVariant,
  GenerationReceipt,
  IntegrityDigest,
  ProvenanceRecord,
  QualityReport
} from './puzzle';
export {
  checkSession,
  clearCell,
  clearEnteredCells,
  createSession,
  enterLetter,
  enterRebus,
  moveSelection,
  patternForEntry,
  revealCell,
  nudgeEntry,
  pauseSession,
  resumeSession,
  selectCell,
  stepEntry,
  touchSession,
  toggleDirection,
  updateActiveTime,
  validateSessionSnapshot,
  validateSolveEvent,
  clearIncorrect,
  hideCheck,
  checksUsed,
  entrySolveState,
  revealsUsed,
  scoreForSession,
} from './session';
export type {
  CheckResult,
  CheckScope,
  CellEvaluation,
  CheckPresentation,
  AssistanceReceipt,
  EntrySolveState,
  EvaluationState,
  EntryStep,
  MoveKey,
  Selection,
  SessionStatus,
  SessionEventType,
  SolveEvent,
  SolveSessionSnapshot
} from './session';